# Generated by Django 6.1.1 on 2026-10-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_tarefa_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(choices=[('fixa', 'Rápida'), ('prolongada', 'Prolongada')], default='fixa', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_area', to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'area')},
            },
        ),
    ]
