# Generated by Django 6.0.6 on 2026-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("senha", models.CharField(max_length=128)),
                ("diretoria", models.CharField(max_length=50)),
                ("areas", models.TextField()),
            ],
        ),
    ]
