# Generated by Django 6.0.6 on 2026-07-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="senha",
            field=models.CharField(max_length=255),
        ),
    ]
