# Generated by Django 6.0.6 on 2026-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_diretoria_publicacao_curtida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicacao",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="diretoria",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Curtida",
        ),
        migrations.DeleteModel(
            name="Publicacao",
        ),
    ]
