# Generated by Django 6.0.6 on 2026-07-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_publicacao_curtida"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="editado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="curtida",
            name="publicacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curtidas",
                to="usuarios.publicacao",
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publicacoes",
                to="usuarios.usuario",
            ),
        ),
    ]
