# Generated by Django 6.0.6 on 2026-07-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_publicacao_editado_alter_curtida_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='doacao_tampinhas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sub_lider',
            field=models.BooleanField(default=False),
        ),
    ]
