# Generated by Django 6.0.6 on 2026-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_usuario_aprovado_usuario_doacao_tampinhas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="sublider_de",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
